export const RUNTIME_MIN_CODE_GEN_SUPPORTED_VERSION =
  "MIN_SUPPORTED_VERSION_0_0_56";

/**
 * A backwards compatibility check.
 *
 * This is the minimum supported version by the current runtime. If you use code generated by a version of TwirpScript lower than this version, you will encounter a TypeScript error instead of any runtime errors.
 *
 * To resolve, run `npx twirpscript` to regenerate the file.
 */
export const MIN_SUPPORTED_VERSION_0_0_56 =
  RUNTIME_MIN_CODE_GEN_SUPPORTED_VERSION;
