// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: src/protos/authentication.proto
import { BinaryReader, BinaryWriter } from "google-protobuf";
import { JSONrequest, PBrequest, createMethodHandler } from "twirpscript";
import type { ClientConfiguration, ServiceHandler } from "twirpscript";

type ByteSource = ArrayBuffer | Uint8Array | number[] | string;

//========================================//
//     Authentication Protobuf Client     //
//========================================//

/**
 * Login in a user
 */
export async function Login(
  credentials: Credentials,
  config?: ClientConfiguration
): Promise<CurrentUser> {
  const response = await PBrequest(
    "/twirp/Authentication/Login",
    Credentials.encode(credentials)
  );
  return CurrentUser.decode(response);
}

//========================================//
//       Authentication JSON Client       //
//========================================//

/**
 * Login in a user
 */
export async function LoginJSON(
  credentials: Credentials,
  config?: ClientConfiguration
): Promise<CurrentUser> {
  const response = await JSONrequest<CurrentUser>(
    "/twirp/Authentication/Login",
    credentials
  );
  return response;
}

//========================================//
//         Authentication Service         //
//========================================//

export interface AuthenticationService<Context = unknown> {
  /**
   * Login in a user
   */
  Login: (
    credentials: Credentials,
    context: Context
  ) => Promise<CurrentUser> | CurrentUser;
}

export function createAuthenticationHandler<Context>(
  service: AuthenticationService<Context>
): ServiceHandler<Context> {
  return {
    path: "Authentication",
    methods: {
      Login: createMethodHandler({
        handler: service.Login,
        encode: CurrentUser.encode,
        decode: Credentials.decode,
      }),
    },
  };
}

//========================================//
//                 Types                  //
//========================================//

export interface CurrentUser {
  username: string;
  token: string;
}

export interface Credentials {
  username: string;
  password: string;
}

//========================================//
//        Protobuf Encode / Decode        //
//========================================//

export namespace CurrentUser {
  export function writeMessage(msg: CurrentUser, writer: BinaryWriter): void {
    if (msg.username) {
      writer.writeString(1, msg.username);
    }
    if (msg.token) {
      writer.writeString(2, msg.token);
    }
  }

  export function encode(currentUser: CurrentUser): Uint8Array {
    const writer = new BinaryWriter();
    writeMessage(currentUser, writer);
    return writer.getResultBuffer();
  }

  export function readMessage(
    msg: Partial<CurrentUser>,
    reader: BinaryReader
  ): void {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.username = reader.readString();
          break;
        }
        case 2: {
          msg.token = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    if (!msg.username) {
      msg.username = "";
    }
    if (!msg.token) {
      msg.token = "";
    }
  }

  export function decode(bytes: ByteSource): CurrentUser {
    const reader = new BinaryReader(bytes);
    const message = {};
    readMessage(message, reader);
    return message as CurrentUser;
  }
}

export namespace Credentials {
  export function writeMessage(msg: Credentials, writer: BinaryWriter): void {
    if (msg.username) {
      writer.writeString(1, msg.username);
    }
    if (msg.password) {
      writer.writeString(2, msg.password);
    }
  }

  export function encode(credentials: Credentials): Uint8Array {
    const writer = new BinaryWriter();
    writeMessage(credentials, writer);
    return writer.getResultBuffer();
  }

  export function readMessage(
    msg: Partial<Credentials>,
    reader: BinaryReader
  ): void {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      const field = reader.getFieldNumber();
      switch (field) {
        case 1: {
          msg.username = reader.readString();
          break;
        }
        case 2: {
          msg.password = reader.readString();
          break;
        }
        default: {
          reader.skipField();
          break;
        }
      }
    }
    if (!msg.username) {
      msg.username = "";
    }
    if (!msg.password) {
      msg.password = "";
    }
  }

  export function decode(bytes: ByteSource): Credentials {
    const reader = new BinaryReader(bytes);
    const message = {};
    readMessage(message, reader);
    return message as Credentials;
  }
}
