import { lowercase, Schema, AUTOGENERATED_NOTICE } from "../utils";

export default function (schema: Schema): string {
  return `${AUTOGENERATED_NOTICE}

import { request } from 'ts-twirp-client/dist/json';
import {
${schema.services
  .map((service) => service.name)
  .concat(schema.messages.map((message) => message.name))
  .sort()
  .map((name) => `  ${name}`)
  .join(",\n")}
} from './types';

${schema.services
  .map(
    (service) =>
      `export function ${service.name}Client(host: string): ${service.name} {
  return {
${service.methods
  .map(
    (method) =>
      `    ${method.name}: function(${lowercase(method.input_type)}: ${
        method.input_type
      }): Promise<${method.output_type}> {
      return request(
        host + '/twirp/${schema.package}/${method.name}',
        ${lowercase(method.input_type)}
      ) as Promise<${method.output_type}>;
    }`
  )
  .join(",\n")}
  };`
  )
  .join("\n\n")}
};`;
}
