// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: bob.proto

import { Timestamp } from "./google/protobuf/timestamp.types";
import { Tate } from "./foo.types";

export interface Person {
  name: string;
  id: number;
  email: string;
  phones: Person.PhoneNumber[];
  last_updated: Timestamp;
}

export namespace Person {
  export enum PhoneType {
    MOBILE = 0,
    HOME = 1,
    WORK = 2,
  }

  export interface PhoneNumber {
    number: string;
    type: Person.PhoneType;
  }

  export interface Bob {
    tate: Tate;
  }
}

export interface AddressBook {
  people: Person[];
}
