name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.publish-local-package.outputs.package }}
    steps:
      - uses: tatethurston/github-actions/publish-local-package@main
        id: publish-local-package
        with:
          path: packages/twirpscript
  ci:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/setup-protoc@v2
        with:
          version: "29.2"
      - uses: tatethurston/github-actions/test@main
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
      - uses: bufbuild/buf-setup-action@v1.25.0
      - uses: tatethurston/github-actions/check-generated-files@main
        with:
          cmd: pnpm regen
  ci-windows:
    name: Windows CI
    runs-on: windows-latest
    needs: build-package
    steps:
      - uses: tatethurston/github-actions/install-local-package@main
        with:
          name: ${{ needs.build-package.outputs.package }}
      - uses: arduino/setup-protoc@v2
        with:
          version: "29.2"
      - name: Bin Check
        run: |
          touch dummy.proto
          npx --no twirpscript
