name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      # Install protoc for e2e:setup
      - uses: arduino/setup-protoc@v2
        with:
          version: "23.4"
      - uses: bufbuild/buf-setup-action@v1.25.0
      - uses: tatethurston/github-actions/test@main
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
      - name: Check for uncommited changes to generated files
        run: |
          pnpm regen
          if git diff --quiet; then
            echo "No changes detected."
          else
            echo "Changes detected:"
            git diff --name-only
            git diff
            echo "Failing build."
            exit 1
          fi
  build_package:
    name: Build Package
    runs-on: ubuntu-latest
    outputs:
      package-name: package-${{ github.event.pull_request.number }}
    steps:
      - uses: tatethurston/github-actions/build@main
      - name: NPM Pack
        run: |
          cd packages/twirpscript
          pnpm pack
          mv *.tgz twirpscript.tgz
      - uses: actions/upload-artifact@v4
        with:
          name: package-${{ github.event.pull_request.number }}
          path: packages/twirpscript/*.tgz
          if-no-files-found: error
          retention-days: 1
          overwrite: true
  check_windows:
    name: Windows CI Check
    runs-on: windows-latest
    needs: build_package
    steps:
      - uses: arduino/setup-protoc@v2
        with:
          version: "23.4"
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build_package.outputs.package-name }}
      - uses: actions/setup-node@v3
      - name: Bin Check
        run: |
          npm install twirpscript.tgz 
          touch dummy.proto
          npx --no twirpscript
